spring:
  mail:
    host: smtp.poczta.onet.pl
    port: 465
    username: proba_spring_email@op.pl
    password: abc123ABC
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          ssl:
            enable: true